version: 2.1
jobs: 
  build:
    docker:
      - image: aboyd88/databus-ci-env:latest
    steps:
      - checkout
      - run:
          name: restore packages
          command: dotnet restore
      - run:
          name: build
          command: dotnet build
      - run:
          name: run unit tests
          command: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - run:
          name: upload coverage reports
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: upload coverage to codacy
          command: cd DataBuses.Tests && cp coverage.opencover.xml opencover.xml && bash <(curl -Ls https://coverage.codacy.com/get.sh)
      - run:
          name: restore packages
          command: dotnet restore
      - run:
          name: push to NuGet
          command: |
            cd DataBuses
            dotnet build --configuration Release
            dotnet pack --output nuget-build --configuration Release
            dotnet nuget push --source "${NUGET_FEED_URL}" --api-key="${NUGET_KEY}" nuget-build/Boyd.DataBuses*.nupkg
            cd ../DataBuses.Interfaces
            dotnet build --configuration Release
            dotnet pack --output nuget-build --configuration Release
            dotnet nuget push --source "${NUGET_FEED_URL}" --api-key="${NUGET_KEY}" nuget-build/Boyd.DataBuses*.nupkg
workflows:
  version: 2
  build:
    jobs:
      - build